import { Metadata } from "next";
import React from "react";
import { fascinate } from "../fonts/font";

export const metadata: Metadata = {
  title: "ecommerce backend",
  description: "generated by create next app",
};
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={`${fascinate.variable}`}>
      <body>{children}</body>
    </html>
  );
};
export default RootLayout;
